name: Workflows Linter

on:
  push:

jobs:
  Actionlint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Download actionlint
        id: get_actionlint
        shell: bash
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)

      - name: Lint
        shell: bash
        run: ${{ steps.get_actionlint.outputs.executable }} -color -shellcheck=
